import * as config from "./config/structs";
import * as currency from "./currency/structs";
import * as kiosk from "./kiosk/structs";
import * as owned from "./owned/structs";
import * as payments from "./payments/structs";
import * as transfers from "./transfers/structs";
import * as treasury from "./treasury/structs";
import * as upgradePolicies from "./upgrade-policies/structs";
import {StructClassLoader} from "../_framework/loader";

export function registerClasses(loader: StructClassLoader) { loader.register(config.Config);
loader.register(config.Issuer);
loader.register(owned.Return);
loader.register(owned.Withdraw);
loader.register(currency.Issuer);
loader.register(currency.Burn);
loader.register(currency.Burned);
loader.register(currency.CurrencyKey);
loader.register(currency.CurrencyLock);
loader.register(currency.Mint);
loader.register(currency.Minted);
loader.register(currency.Update);
loader.register(kiosk.Issuer);
loader.register(kiosk.KioskOwnerKey);
loader.register(kiosk.KioskOwnerLock);
loader.register(kiosk.List);
loader.register(kiosk.Take);
loader.register(treasury.Issuer);
loader.register(treasury.Open);
loader.register(treasury.Spend);
loader.register(treasury.Treasury);
loader.register(treasury.TreasuryKey);
loader.register(payments.Issuer);
loader.register(payments.ClaimCap);
loader.register(payments.Pay);
loader.register(payments.Stream);
loader.register(payments.StreamCreated);
loader.register(transfers.Issuer);
loader.register(transfers.Transfer);
loader.register(upgradePolicies.Issuer);
loader.register(upgradePolicies.Restrict);
loader.register(upgradePolicies.Restricted);
loader.register(upgradePolicies.TimeLock);
loader.register(upgradePolicies.TimeLockKey);
loader.register(upgradePolicies.Upgrade);
loader.register(upgradePolicies.UpgradeKey);
loader.register(upgradePolicies.UpgradeLock);
loader.register(upgradePolicies.Upgraded);
 }
