import * as account from "./account/structs";
import * as config from "./config/structs";
import * as kiosk from "./kiosk/structs";
import * as multisig from "./multisig/structs";
import * as owned from "./owned/structs";
import * as payments from "./payments/structs";
import * as transfers from "./transfers/structs";
import * as upgradePolicies from "./upgrade-policies/structs";
import {StructClassLoader} from "../_framework/loader";

export function registerClasses(loader: StructClassLoader) { loader.register(multisig.Executable);
loader.register(multisig.Member);
loader.register(multisig.Multisig);
loader.register(multisig.Proposal);
loader.register(account.Account);
loader.register(account.Invite);
loader.register(config.Witness);
loader.register(config.Migrate);
loader.register(config.Modify);
loader.register(kiosk.Witness);
loader.register(kiosk.KioskOwnerLock);
loader.register(kiosk.List);
loader.register(kiosk.Take);
loader.register(owned.Return);
loader.register(owned.Withdraw);
loader.register(payments.Witness);
loader.register(payments.Pay);
loader.register(payments.Stream);
loader.register(transfers.Witness);
loader.register(transfers.Deliver);
loader.register(transfers.Delivery);
loader.register(transfers.DeliveryCap);
loader.register(transfers.Send);
loader.register(upgradePolicies.Witness);
loader.register(upgradePolicies.Restrict);
loader.register(upgradePolicies.TimeLock);
loader.register(upgradePolicies.Upgrade);
loader.register(upgradePolicies.UpgradeLock);
 }
